### ISSUE TITLE
Not working with matlab 2016

### ISSUE THREAD

**Issue by eshafeeqe** [pglira/Point_cloud_tools_for_Matlab#1]
I am getting following error while executing command to make a point cloud. 

>> pc = pointCloud('Lion.xyz');
pc.plot;
Error using pointCloud
Error: File: pointCloud.m Line: 403 Column: 9
A constructor call to superclass KDTreeSearcher appears after the object is used, or after a return.

I am using ubuntu 14.04.

**Comment by jandob** [comment]
Got the same error, i think its because matlab now has its builtin pointCloud class.

**Comment by pglira** [comment]
Hi, I commited a major update for the pointCloud class. Your issue is solved now, as the point cloud class is no longer a subclass of the KDTreeSearcher class.
