### ISSUE TITLE
Problems when using 'SubsetRadius' parameter

### ISSUE THREAD

**Issue by pabloinigoblasco** [pglira/Point_cloud_tools_for_Matlab#3]
Hello.
When the 'SubsetRadius' parameter is used in the RunICP method I get the following error:

No appropriate method, property, or field 'rangesearch' for class 'pointCloud'.

> Error in runICPSubsets (line 17)
>     idxRangeSearch = PC{i}.rangesearch(allQP, p.SubsetRadius);
> 
> Error in globalICP/runICP (line 219)
>         [g, PC] = runICPSubsets(obj, p, g, PC);
> 
> Error in testICPPhilipGira (line 175)
> icp.runICP(ICPOptions);
> 

It looks like you are using some library that contains that function. Where is located that function?
Thanks in advance.

**Comment by pglira** [comment]
Thank you for this bug report, it's fixed now. It should work after updating the file [runICPSubsets.m](https://github.com/pglira/Point_cloud_tools_for_Matlab/blob/master/classes/%40globalICP/private/runICPSubsets.m) to the current version.
