### ISSUE TITLE
GlobalICP Corresponding Pairs Visualization

### ISSUE THREAD

**Issue by MINDoSOFT** [pglira/Point_cloud_tools_for_Matlab#4]
Hello,

thank you for this excellent library.

I am facing a challenge. I need a way to visualize the corresponding pairs (between the two point clouds), to verify their accuracy. 

Because I am getting an alignment between two point clouds that is not accurate and I want to improve it, but first I want to make sure that the matches are accurate.

How would this be possible using this library? 

Thank you for your help.

**Comment by pglira** [comment]
Hi,

you can access the matches after the ICP for a specific pair (`idxPair`):
- points from point cloud 1: `icp.CP.PostICP{idxPair}.X1`
- points from point cloud 2: `icp.CP.PostICP{idxPair}.X2`

Their point-to-plane distances are saved in `icp.CP.PostICP{idxPair}.dp`

Hope this helps!
