### ISSUE TITLE
GlobalICP Kinect v1 Point Cloud Data

### ISSUE THREAD

**Issue by MINDoSOFT** [pglira/Point_cloud_tools_for_Matlab#5]
Hello again.

I am trying to align two relatively close point clouds, captured using Kinect v1 and I am having a hard time achieving it using GlobalICP.

I'd like some help with the various parameters that can be adjusted.

Currently I have adjusted HullVoxelSize to be 0.25 and the output says "Overlapping voxels 348". Is this a logical value for my kind of scene? (See screenshot below)

Also UniformSamplingDistance has been adjusted to be 0.25 to increase the number of correspondences found. Because otherwise I got an exception like the following: 
`GLOBALICP > RUNICP > ICP ITERATION 4 OF 10 > MINIMIZATION : attention, point cloud [1] has only 4 correspondences!`

And increasing MaxNoIt does not seem to improve the alignment.

Here you can see the 2 point clouds that I want to align before and after GlobalICP:

![image](https://user-images.githubusercontent.com/890368/36225787-77c2010e-11d4-11e8-8bf9-4c0a0dfc58ce.png)

![image](https://user-images.githubusercontent.com/890368/36225337-06654b2a-11d3-11e8-9fd1-327869e1f7e7.png)

Thank you for your help and time.

**Comment by pglira** [comment]
Hi, I can't distinguish the two point clouds on the screenshots. The parameters for voxelSize and uniformSampling should be ok, however, to find out what's the problem I would need the data itself.

**Comment by MINDoSOFT** [comment]
Here are the images of the point clouds (png format):

![img_0001](https://user-images.githubusercontent.com/890368/36267913-cd893946-127d-11e8-99f8-277bfeffd8b8.png)

![img_0050](https://user-images.githubusercontent.com/890368/36267938-e5096852-127d-11e8-8307-7aba862d0ada.png)

And the point cloud files themselves (ply format) can be downloaded from [here](https://drive.google.com/open?id=1302XIE2g7QdMrtU5W-EQVLr_B5li__EX).

Thank you.

**Comment by pglira** [comment]
Hi, this is working:
```
icp = globalICP;

icp.addPC('00001.ply');
icp.addPC('00050.ply');

ICPOptions.MaxNoIt                  = 20;
% ICPOptions.IdxFixedPointClouds      = ;
% ICPOptions.NoOfTransfParam          = ;
ICPOptions.HullVoxelSize            = 0.25;
ICPOptions.UniformSamplingDistance  = 0.1;
ICPOptions.PlaneSearchRadius        = 0.2;
% ICPOptions.WeightByRoughness        = ;
% ICPOptions.WeightByDeltaAngle       = ;
ICPOptions.MaxDeltaAngle            = 10;
ICPOptions.MaxDistance              = 1;
ICPOptions.MaxSigmaMad              = Inf;
ICPOptions.MaxRoughness             = 0.1;
% ICPOptions.LogLevel                 = ;
ICPOptions.Plot                     = true;
% ICPOptions.SubsetRadius             = ;
% Undocumented parameters
% ICPOptions.PairList                 = ;
% ICPOptions.RandomSubsampling        = ;
% ICPOptions.NormalSubsampling        = ;
% ICPOptions.MaxLeverageSubsampling   = ;
% ICPOptions.SubsamplingPercentPoi    = ;
% ICPOptions.AdjOptions               = ;
% ICPOptions.MinNoIntersectingVoxel   = ;
% ICPOptions.TrafoOriginalPointClouds = ;
% ICPOptions.StopConditionNormdx      = ;

icp.runICP(ICPOptions);
```
The initial alignment of the two point clouds is not very good, thus I used very weak rejection criteria. In order to further improve the registration of the point clouds another run with "normal" parameters might be useful.

**Comment by MINDoSOFT** [comment]
Yes I have run GlobalICP with the parameters you mention and indeed the result seems to be aligned but not totally.

Is it enough to run 
```
icp.runICP(ICPOptions);
icp.runICP(); 
```

or do I need to 
`icp.exportPC(ii, outPointCloudFileName);`

and then add the "aligned" files exported using
`icp.addPC(pointCloudFileName);`

to run GlobalICP for a second time with default parameters.

The reason why I'm asking is because I've run it using the first method I mention here and I get the following exception:
```
                         | T : NUMBER OF CORRESPONDENCES FOR EACH POINT CLOUD:
                         | T :  point cloud   corresp.    file
                         | T :          [1]          3    00001_POSTICP
                 +0.006s | X : GLOBALICP > RUNICP > ICP ITERATION 2 OF 5 > MINIMIZATION : attention, point cloud [1] has only 3 correspondences!
                         | T :          [2]          3    00050_POSTICP
                 +0.010s | X : GLOBALICP > RUNICP > ICP ITERATION 2 OF 5 > MINIMIZATION : attention, point cloud [2] has only 3 correspondences!
                         | T : -------------------------------------------------------------------------------
Undefined function or variable 'idxPrm'.
```

Thanks.

**Comment by pglira** [comment]
Simply change the parameters `MaxDistance` and `MaxSigmaMad` after the first run and repeat the ICP:

```
icp = globalICP;

icp.addPC('00001.ply');
icp.addPC('00050.ply');

ICPOptions.MaxNoIt                  = 20;
% ICPOptions.IdxFixedPointClouds      = ;
% ICPOptions.NoOfTransfParam          = ;
ICPOptions.HullVoxelSize            = 0.25;
ICPOptions.UniformSamplingDistance  = 0.1;
ICPOptions.PlaneSearchRadius        = 0.2;
% ICPOptions.WeightByRoughness        = ;
% ICPOptions.WeightByDeltaAngle       = ;
ICPOptions.MaxDeltaAngle            = 10;
ICPOptions.MaxDistance              = 1;
ICPOptions.MaxSigmaMad              = Inf;
ICPOptions.MaxRoughness             = 0.1;
% ICPOptions.LogLevel                 = ;
ICPOptions.Plot                     = true;
% ICPOptions.SubsetRadius             = ;
% Undocumented parameters
% ICPOptions.PairList                 = ;
% ICPOptions.RandomSubsampling        = ;
% ICPOptions.NormalSubsampling        = ;
% ICPOptions.MaxLeverageSubsampling   = ;
% ICPOptions.SubsamplingPercentPoi    = ;
% ICPOptions.AdjOptions               = ;
% ICPOptions.MinNoIntersectingVoxel   = ;
% ICPOptions.TrafoOriginalPointClouds = ;
% ICPOptions.StopConditionNormdx      = ;

icp.runICP(ICPOptions);

close

ICPOptions.MaxDistance              = 0.2;
ICPOptions.MaxSigmaMad              = 3;

icp.runICP(ICPOptions);

```

After that you can export the final point clouds.

These are my final alignment results:
```
                         | B | T : -------------------------------------------------------------------------------
                         | B | T : POINT CLOUD DEPENDANT STATISTICS:
                         | B | T :  point_cloud     corresp.      std(dp)     mean(dp)     file
                         | B | T :          [1]          779      0.00706     -0.00001     00001_POSTICP
                         | B | T :          [2]          779      0.00706     -0.00001     00050_POSTICP
                         | B | T : where dp = vector of all (signed) point-to-plane distances associated to a single point cloud
                         | B | T : -------------------------------------------------------------------------------
```
